AngryVillagerParticle: false
FlameParticle: false
EndermanTeleportParticle: false
LavaParticle: true
WaterParticle: false
InkPrticle: false
SmokeParticle: false
HeartParticle: false
#change false to true to work that particle!
